type Error = { code:int; reason:string }
type Address = { address:string? }
type Place = Address with { name:string }
type Places = { places: Place* }
type Empty = {}

service places [/places] {
	list:   => Places = GET
    create: Place => Place or Error = POST
}

service place(Place) [/places/<name>] {
   	get: => Place or Error = GET
   	update: Address => Place or Error = PUT
   	delete: => Empty or Error = DELETE
}

client placesRest1 provides places
client placesRest2 provides places, place
